# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d64904aac9d1a67416ba38d80af026d1"
name = "seo-bulk-updater"
application_url = "https://seo-bulk-updater.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_products,write_discounts,write_products"

[auth]
redirect_urls = [ "https://seo-bulk-updater.vercel.app/auth/callback" ]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[app_proxy]
url = "https://seo-bulk-updater.vercel.app"
subpath = "seo-bulk-updater-proxy"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
